### ISSUE TITLE
Infografia_antonia mtz sandoval

### ISSUE THREAD

**Issue by 2003lulu** [SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-2003lulu#1]
[Infografía_ANTONIA MTZ SANDOVAL.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-infograf-a-de-calidad-de-software-2003lulu/files/15490108/Infografia_ANTONIA.MTZ.SANDOVAL.pdf)

**Comment by josealfredo79** [comment]
Calificacion 20
